### PR TITLE
Add display_name modification in insights_register.py

### PR DESCRIPTION
**Pull request by kubealex**
Cleaned up #50 due to some conflicts with different histories on my workstations.

Original PR:
---
As of now, the variable is never uses, making it useless.
I added a check and edited the command accordingly.

### CODE REVIEW

**Comment by ptoscano** [comment]
Thanks for the update, and no worries for the old PR ;)

In general the change LGTM; a descriptive commit message was lost in the old PR, so would it be possible to amend it? From the old PR, it could be something like:
```
fix: use display_name variable in insights_register

As of now, the variable is never uses, making it useless.
I added a check and edited the command accordingly.
```
Thanks!

**Comment by kubealex** [comment]
Done, thank you @ptoscano!

**Review by ptoscano — APPROVED** [review]
Thanks for the updates, LGTM now.

Side note while I reviewed this: apparently the `force_reregister` has been broken for a while, since that option calls `insights-client --force-reregister`, which is no more usable:
https://github.com/RedHatInsights/insights-core/blob/547457c8d5a92ca66403405fba41be81edce9a97/insights/client/config.py#L696-700

:facepalm: 

Nothing that blocks this change though.

**Comment by ptoscano** [comment]
Ah, side note: I'm working on updating this collection for newer versions of Ansible, see PR #56. I needed to do a small change to the default of `display_name` to be `None` instead of `''`; although I don't think it should affect your code (since it does `if display_name:`).

Since you use that feature, would it be possible to test that PR, and check it works fine in your playbooks/environments?

Thanks in advance!

**Comment by kubealex** [comment]
tested, it doesn't conflict at all and it works! 
btw I created a new PR to overcome the --force-reregister deprecation (#57) :)

**Pull request merged**
